### PR TITLE
fix: handle errors in closures [1.x]

### PR DESCRIPTION
**Pull request by jaulz**
When you pass a closure instead of a class there is obviously no `failed` method which can be called in case of a failure. This PR adds a simple check and let's the exception bubble up.

I raised the PR to 1.x (because that's what I use with Tenancy package) but can of course adapt the changes to 2.x as well if you want.

### CODE REVIEW

**Comment by stancl** [comment]
Could you add some tests?

**Comment by jaulz** [comment]
@stancl sorry for the delay but finally I could manage to work on it 😊

**Comment by jaulz** [comment]
@stancl okay, I noticed that the proposed change is maybe just too much. Instead I could simply rely on a closure but the issue right now is that errors are not handled properly. My recent changes should fix it with minimal invasion. Could you please have another look?

**Comment by stancl** [comment]
Can you update the PR desc?

**Comment by jaulz** [comment]
@stancl sorry, done 😊

**Comment by stancl** [comment]
Bit confused about what exactly the test is doing. The entire try-catch is _inside_ the closure?

**Comment by jaulz** [comment]
Oh, wow, you were right... seems I was very tired and too happy that the test executed at all 😁 I hope it's now working better.

**Comment by stancl** [comment]
The diff looks good now. I've confirmed the added test fails without the change. Can you open an additional PR for the 2.x branch? I'd merge them at once.

**Pull request merged**
