### PR TITLE
Possibility to change the default configurations for the queue jobs.

### PR DESCRIPTION
**Pull request by jonathanpmartins**
This pull request enables me to change the queue name that the JobPipeline will be pushed to.

Now I can do something like this:
```php
JobPipeline::make([
    Jobs\CreateDatabase::class,
    Jobs\MigrateDatabase::class,
    // Jobs\SeedDatabase::class,

    // Your own jobs to prepare the tenant.
    // Provision API keys, create S3 buckets, anything you want!

])->send(function (Events\TenantCreated $event)
{
    return $event->tenant;
})->onQueue('another-queue')
    ->shouldBeQueued()
```

### CODE REVIEW

**Comment by stancl** [comment]
Looks good. Maybe we could also add a second arg to `->shouldBeQueued()` so that a single method call can be used (when the use case allows it)?
```php
shouldBeQueued(true, 'another-queue');
shouldBeQueued(queue: 'another-queue'); // equivalent to the above

shouldBeQueued($condition, 'another-queue');
```

This won't work every time so having two separate methods is good, but letting people make just a single call when it works for them would be useful here I think.

**Comment by jonathanpmartins** [comment]
Agreed, I think it would be very nice! I can do another pull request if you want to.

**Comment by jonathanpmartins** [comment]
I think I will do another pull request, with the other calls, `onConnection`, `delay`, `tries`, and so on...

**Comment by stancl** [comment]
You can make changes in the existing PR, no need to open a new one

**Comment by stancl** [comment]
Just push changes to your `master` since that's the branch the PR is opened from 👍🏻

**Comment by jonathanpmartins** [comment]
I added the following methods: `onConnection`, `onQueue`, `timeout` ,`delay`, `tries` and `shouldBeQueuedOn`.

I changed the signature of the `shouldBeQueued` method too. What do you think of this approach? The user will be able to call `shouldBeQueued('queue-name')` with the name directly.

**Comment by jonathanpmartins** [comment]
I think that's it. The only problem is that there is no tests for all these new methods.

**Comment by jonathanpmartins** [comment]
Do you need tests for all new functions to pass this pull request?

**Comment by stancl** [comment]
Yeah everything should be tested.

Also if we're changing the `shouldBeQueued()` method, the new argument should have a default value. Otherwise I'd have to make this a new major release (which I'm willing to do, since this package is pretty simple).

**Comment by stancl** [comment]
Seems like the second arg isn't implemented yet. I'd prefer this https://github.com/archtechx/jobpipeline/pull/13#issuecomment-1445129865 over the current code in the PR.

**Comment by jonathanpmartins** [comment]
will update the PR until tomorrow

**Comment by jonathanpmartins** [comment]
I removed the other methods as they don't have tests.

**Comment by stancl** [comment]
Apologies that I didn't get to this for two weeks. Finished the PR now and merged it. Appreciate your work on this!

I'll make a new major release since we changed the method signature. We'll use that version in v4 👍🏻. Might make it an rc for now in case we need to make some more changes before v4 release.

**Comment by jonathanpmartins** [comment]
No problems. This is all open source!
If you want to improve upon this changes and need some help, I'm happy to help!
Would be nice to have an open issue with all pretended changes listed as topics.
I would make the changes and you would supervise it!

**Comment by jonathanpmartins** [comment]
As the version upgrade let us change the signature of some functions, I would like to point out the changes made in this commit: 
https://github.com/archtechx/jobpipeline/pull/13/commits/7e618f6950e334b1eab3e298f43ecf8ec59389f9

As a long time Laravel user the changes that I made in the commit above seems natural and integrated with the Laravel flow. The code in focus is this one:

```php
    public function shouldBeQueued(bool|string $shouldBeQueued = true)
    {
        if (is_string($shouldBeQueued))
        {
            $this->onQueue($shouldBeQueued);
            $this->shouldBeQueued = true;
        }
        else
        {
            $this->shouldBeQueued = $shouldBeQueued;
        }

        return $this;
    }
```

It is 100% back compatible as the user can still pass a boolean or not. It is simple as just passing a `string` sends it to another queue. The docs can be updated to indicate this new behavior in the new version. 

That other new public functions previously added https://github.com/archtechx/jobpipeline/pull/13#issuecomment-1445136005 and than removed could be bring back with tests. Just thoughts...

What do you thing about this approach?

**Comment by stancl** [comment]
> Would be nice to have an open issue with all pretended changes listed as topics.
I would make the changes and you would supervise it!

If you have any more suggested changes feel free to open issues and I'll take a look at them.

re: second comment — there may be use cases where people want to define the queue but determine whether the job should be queued separately. And since PHP 8, mixing types isn't generally a good idea unless there's a major benefit. 

`bool|string $shouldBeQueued = true` is indeed Laravely syntax but it's a bit "legacy" in the sense that now you can just do `queue: 'another'` and the code is much cleaner with all variables having their own meaning and type.

**Pull request merged**
